#!/bin/bash

# This script runs the integration tests on an already configured LXD machine
# where the tests are run LXD in LXD.  i.e. an LXD container is spawned, pylxd
# is copied into the container, and then the container runs the integration
# tests.

# This script is NOT used by the CI system, but for people to run integration
# tests on their own computers where they don't want the integration test to
# mess with their setup.

set -ex

_dir="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"

function _run_tests {
	local _target=${1}
	CONTAINER_NAME=pylxd-$_target-`uuidgen | cut -d"-" -f1`

	if [[ "${_target}" == "focal" ]]; then
		echo "Running Focal (20:04) integration tests"
		CONTAINER_IMAGE="ubuntu:20.04"
	elif [[ "${_target}" == "bionic" ]]; then
		echo "Running Bionic (18:04) integration tests"
		CONTAINER_IMAGE="ubuntu:18.04"
	else
	    exit
	fi

	lxc launch $CONTAINER_IMAGE $CONTAINER_NAME -c security.nesting=true
	lxc exec $CONTAINER_NAME -- cloud-init status --long --wait

	local ldir="${_dir}/.."
	lxc file push --create-dirs --recursive ${ldir} ${CONTAINER_NAME}/opt/
	lxc exec $CONTAINER_NAME -- /bin/sh -c "cd /opt/pylxd && integration/run-integration-tests"

	lxc delete --force $CONTAINER_NAME
}

# run focal and then bionic integration tests
_run_tests focal
_run_tests bionic
